<?php

namespace Packfire\Session\Storage;

use Packfire\Session\Storage\SessionStorage;
use Packfire\FuelBlade\Container;

/**
 * Test class for Messenger.
 * Generated by PHPUnit on 2012-07-13 at 12:14:49.
 */
class SessionStorageTest extends \PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        TestState::reset();
    }

    public function testId()
    {
        $obj = new SessionStorage();
        $this->assertEquals('default', $obj->id());
    }

    public function testGet()
    {
        $obj = new SessionStorage();
        $this->assertNull($obj->get('NULL_KEY'));
        $this->assertEquals(10, $obj->get('NULL_KEY', 10));
    }

    public function testRemove()
    {
        $obj = new SessionStorage();
        $obj->set('key', true);
        $this->assertTrue($obj->get('key'));
        $obj->remove('key');
        $this->assertNull($obj->get('key'));
    }

    public function testClear()
    {
        $obj = new SessionStorage();
        $obj->set('key', true);
        $obj->clear();
        $this->assertNull($obj->get('key'));
    }

    public function testRegenerate()
    {
        $this->assertNull(TestState::$lastCalled);

        $obj = new SessionStorage();
        $obj->regenerate(true);
        $this->assertEquals('session_regenerate_id', TestState::$lastCalled);
        $this->assertEquals(true, TestState::$lastCalledArgs[0]);
    }

    public function testRegisterHandler()
    {
        $this->assertNull(TestState::$lastCalled);

        $obj = $this->getMockForAbstractClass('Packfire\Session\MockSessionStorage');
        $this->assertEquals('session_set_save_handler', TestState::$lastCalled);
        $this->assertCount(6, TestState::$lastCalledArgs);
    }
}
